name: Build
on:
  pull_request:
      types: [opened, reopened]


  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Fetch the latest release of Infrarust
        run: gh release download -R shadowner/infrarust -p 'infrarust-linux-x86_64.tar.gz'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract the latest release of Infrarusts
        run: tar -xvf infrarust-linux-x86_64.tar.gz

      - name: Build the latest Docker image
        run:  docker build . --file Dockerfile --tag shadowner/infrarust-egg:latest